import DummyPic from "../../../Images/DummyPic.png";
const dummyConversations = [
	{
		id: 1,
		name: "John Smith",
		message: "Hello, I need assistance with my order.",
		timestamp: "01-05-2024, 05:45 Pm",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 2,
		name: "Emma Johnson",
		message: "I have a question about my subscription.",
		timestamp: "01-05-2024, 06:15 Pm",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
	{
		id: 3,
		name: "Michael Brown",
		message: "Can you help me with a refund?",
		timestamp: "01-06-2024, 09:30 Am",
		status: "completed",
		avatar: `${DummyPic}`,
	},
	{
		id: 4,
		name: "Sarah Davis",
		message: "I'm having trouble logging in.",
		timestamp: "01-06-2024, 11:20 Am",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 5,
		name: "David Wilson",
		message: "How do I update my payment method?",
		timestamp: "01-06-2024, 02:45 Pm",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
	{
		id: 6,
		name: "Jennifer Taylor",
		message: "I need help with product installation.",
		timestamp: "01-07-2024, 10:00 Am",
		status: "completed",
		avatar: `${DummyPic}`,
	},
	{
		id: 7,
		name: "Robert Anderson",
		message: "Can you explain the warranty policy?",
		timestamp: "01-07-2024, 01:30 Pm",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 8,
		name: "Lisa Thomas",
		message: "I have a suggestion for improvement.",
		timestamp: "01-08-2024, 09:15 Am",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
	{
		id: 9,
		name: "William Clark",
		message: "How do I track my order?",
		timestamp: "01-08-2024, 11:45 Am",
		status: "completed",
		avatar: `${DummyPic}`,
	},
	{
		id: 10,
		name: "Mary Rodriguez",
		message: "I need to change my delivery address.",
		timestamp: "01-08-2024, 03:20 Pm",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 11,
		name: "James Lee",
		message: "Can you help me with product comparison?",
		timestamp: "01-09-2024, 10:30 Am",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
	{
		id: 12,
		name: "Patricia White",
		message: "I have a question about the return policy.",
		timestamp: "01-09-2024, 02:00 Pm",
		status: "completed",
		avatar: `${DummyPic}`,
	},
	{
		id: 13,
		name: "Richard Harris",
		message: "How do I cancel my subscription?",
		timestamp: "01-10-2024, 09:45 Am",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 14,
		name: "Linda Martin",
		message: "I need assistance with product setup.",
		timestamp: "01-10-2024, 11:30 Am",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
	{
		id: 15,
		name: "Thomas Moore",
		message: "Can you explain the shipping options?",
		timestamp: "01-10-2024, 03:15 Pm",
		status: "completed",
		avatar: `${DummyPic}`,
	},
	{
		id: 16,
		name: "Barbara Jackson",
		message: "I have a billing inquiry.",
		timestamp: "01-11-2024, 10:00 Am",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 17,
		name: "Joseph Thompson",
		message: "How do I reset my password?",
		timestamp: "01-11-2024, 01:45 Pm",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
	{
		id: 18,
		name: "Susan Garcia",
		message: "I need help with product customization.",
		timestamp: "01-12-2024, 09:30 Am",
		status: "completed",
		avatar: `${DummyPic}`,
	},
	{
		id: 19,
		name: "Charles Martinez",
		message: "Can you assist with account deletion?",
		timestamp: "01-12-2024, 11:15 Am",
		status: "closed",
		avatar: `${DummyPic}`,
	},
	{
		id: 20,
		name: "Margaret Robinson",
		message: "I have a question about gift cards.",
		timestamp: "01-12-2024, 02:30 Pm",
		status: "reopen",
		avatar: `${DummyPic}`,
	},
];

export default dummyConversations;
